### ISSUE TITLE
Failed for varnish ld libGeoIP

### ISSUE THREAD

**Issue by soarpenguin** [cosimo/varnish-geoip#8]
error message like:

Message from dlopen:
Compiled VCL program failed to load:
  ./vcl.pmCq19vo.so: undefined symbol: GeoIP_open_type
Running dlopen failed, exit 1

VCL compilation failed

----------------------------------
i installed geoip like:

$ ll /usr/lib/libGeoIP.*
-rw-r--r-- 1 root root 1345150 Jul 13 16:21 /usr/lib/libGeoIP.a
-rwxr-xr-x 1 root root     921 Jul 13 16:21 /usr/lib/libGeoIP.la
lrwxrwxrwx 1 root root      17 Jul 13 16:21 /usr/lib/libGeoIP.so -> libGeoIP.so.1.6.5
lrwxrwxrwx 1 root root      17 Jul 13 16:21 /usr/lib/libGeoIP.so.1 -> libGeoIP.so.1.6.5
-rwxr-xr-x 1 root root  655553 Jul 13 16:21 /usr/lib/libGeoIP.so.1.6.5

$ ll /usr/include/GeoIP*
-rw-r--r-- 1 root root 20586 Jul 13 16:21 /usr/include/GeoIP.h
-rw-r--r-- 1 root root  2460 Jul 13 16:21 /usr/include/GeoIPCity.h

@cosimo  thk for your attention.

**Comment by cosimo** [comment]
Hi!

How are you starting up varnish?
The error message seems to imply that you haven't added the `-lGeoIP` option to the linker command. If that's the case, please check this page for further help:

http://stackoverflow.com/questions/5906603/varnish-daemon-opts-options-errors/8333333#8333333

**Comment by soarpenguin** [comment]
tks for your reply, i have solved it.
just add some opts in /etc/sysconfig/varnish
 -p 'cc_command=exec cc -fpic -shared -Wl,-x -L/usr/include/GeoIP.h -L/usr/lib -lGeoIP -o %o %s'
